version: '3.8'
services:
  mypostgresdb:
    image: postgres:13.0-alpine
    volumes:
      - /var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
    env_file:
      - ./.env
  web:
    build: ../app
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - static_value:/app/static/
    depends_on:
      - mypostgresdb
    env_file:
      - ./.env

volumes:
  static_value: